name: tolyui_navigation
description: "Part of Toly UI: Navigation UI Widget Lib. Contains breadcrumb、drop_menu、rail_menu_tree、tabs etc..."
version: 0.0.8+5
homepage: https://github.com/TolyFx/toly_ui
repository: https://github.com/TolyFx/toly_ui/tree/main/modules/tolyui_navigation

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tolyui_feedback: ^0.3.4
#  tolyui_feedback:
#    path: ../tolyui_feedback

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  tolyui_feedback:
    path: ../tolyui_feedback

flutter:

