name: tolyui_navigation
description: "Part of Toly UI: Navigation UI Widget Lib. Contains breadcrumbã€drop_menuã€rail_menu_treeã€tabs etc..."
version: 0.1.0
homepage: https://github.com/TolyFx/toly_ui
repository: https://github.com/TolyFx/toly_ui/tree/main/modules/tolyui_navigation

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tolyui_feedback: 0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

